name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request: {}

jobs:
  test:
    name: Test (Node)
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-22.04, windows-2022]
        # https://nodejs.org/en/about/releases/
        node-version: ['10', '12', '14', '16', '18', '20']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Test (Integration)
        # https://github.com/webpack/webpack/issues/14532
        if: ${{ matrix.node-version != '18' && matrix.node-version != '20' }}
        run: |
          cd ./tests/integration/rollup-test && ./test.sh && cd -
          cd ./tests/integration/webpack-babel-test && ./test.sh && cd -
          cd ./tests/integration/webpack-test && ./test.sh && cd -

  browser:
    name: Test (Browser)
    runs-on: 'ubuntu-latest'
    container:
      image: mcr.microsoft.com/playwright:v1.17.1-focal
      options: --ipc=host --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Take ownership of workspace
        run: |
          chown -R root:root "$GITHUB_WORKSPACE"
          chmod -R u+rwX "$GITHUB_WORKSPACE"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx grunt prepare

      - name: Test
        run: npm run test:browser
